apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-producer-consumer-config
  namespace: default
  labels:
    app: elastic-producer-consumer
data:
  application.conf: |
    elastic {
      host = ${ELASTIC_HOST}
      port = ${ELASTIC_PORT}
      protocol = ${ELASTIC_PROTOCOL}
      username = ${ELASTIC_USERNAME}
      password = ${ELASTIC_PASSWORD}
      
      producer {
        index = ${PRODUCER_INDEX}
        batch-size = ${PRODUCER_BATCH_SIZE}
        flush-interval = ${PRODUCER_FLUSH_INTERVAL}
        records-per-day = ${PRODUCER_RECORDS_PER_DAY}
      }
      
      consumer {
        source-index = ${CONSUMER_SOURCE_INDEX}
        offset-index = ${CONSUMER_OFFSET_INDEX}
        consumer-id = ${CONSUMER_ID}
        batch-size = ${CONSUMER_BATCH_SIZE}
        poll-interval = ${CONSUMER_POLL_INTERVAL}
        scroll-timeout = ${CONSUMER_SCROLL_TIMEOUT}
      }
    }
    
    logging {
      level = ${LOG_LEVEL}
    }
    
    health {
      port = ${HEALTH_PORT}
    }
    
    metrics {
      enabled = ${METRICS_ENABLED}
    }
  
  logback.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n</pattern>
            </encoder>
        </appender>
        
        <logger name="com.example" level="DEBUG" additivity="false">
            <appender-ref ref="STDOUT"/>
        </logger>
        
        <root level="INFO">
            <appender-ref ref="STDOUT"/>
        </root>
    </configuration>