apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-producer-consumer
  namespace: default
  labels:
    app: elastic-producer-consumer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastic-producer-consumer-role
  labels:
    app: elastic-producer-consumer
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elastic-producer-consumer-binding
  labels:
    app: elastic-producer-consumer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elastic-producer-consumer-role
subjects:
- kind: ServiceAccount
  name: elastic-producer-consumer
  namespace: default