apiVersion: v1
kind: Service
metadata:
  name: elastic-producer-service
  namespace: default
  labels:
    app: elastic-producer
    component: producer
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: health
    protocol: TCP
    name: health
  selector:
    app: elastic-producer
    component: producer

---
apiVersion: v1
kind: Service
metadata:
  name: elastic-consumer-service
  namespace: default
  labels:
    app: elastic-consumer
    component: consumer
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: health
    protocol: TCP
    name: health
  selector:
    app: elastic-consumer
    component: consumer